import { withLensPreset, defaultSpec, type SplitSpec } from './split';

/**
 * The three shipped presets (plan Phase 3 Sitting B §6, amended 2026-09-17). They are generated by
 * the engine, never drawn by hand: `npm run presets -w app` regenerates packs/ (repo root) from these
 * specs, and src/splitter/presets.test.ts fails if the committed packs no longer match.
 */

/** Today's legislatures, [lng, lat]: the 13 provincial and territorial capitals, then Ottawa. */
export const CAPITALS: { name: string; point: [number, number] }[] = [
  { name: "St. John's", point: [-52.7126, 47.5615] },
  { name: 'Charlottetown', point: [-63.1311, 46.2382] },
  { name: 'Halifax', point: [-63.5752, 44.6488] },
  { name: 'Fredericton', point: [-66.6431, 45.9636] },
  { name: 'Québec', point: [-71.2143, 46.8081] },
  { name: 'Toronto', point: [-79.3957, 43.6629] },
  { name: 'Winnipeg', point: [-97.147, 49.8844] },
  { name: 'Regina', point: [-104.6153, 50.4321] },
  { name: 'Edmonton', point: [-113.5064, 53.5335] },
  { name: 'Victoria', point: [-123.37, 48.4197] },
  { name: 'Whitehorse', point: [-135.0523, 60.7197] },
  { name: 'Yellowknife', point: [-114.3718, 62.454] },
  { name: 'Iqaluit', point: [-68.517, 63.7467] },
  { name: 'Ottawa', point: [-75.7009, 45.4236] },
];

export interface Preset {
  id: string;
  name: string;
  description: string;
  spec: SplitSpec;
}

const base = defaultSpec();

export const PRESETS: Preset[] = [
  {
    id: 'alberta-15',
    name: 'Alberta in 15 (economic lens)',
    description: 'Alberta bisected on the Economic lens until there are 15 regions, balanced by population.',
    spec: {
      ...withLensPreset(
        { ...base, scope: { kind: 'province', province: 'AB' }, method: 'lens', n: 15, seed: 15 },
        'economic',
      ),
    },
  },
  {
    id: 'canada-26',
    name: 'Canada in 26 (internal-colony index)',
    description:
      'Canada bisected on the internal-colony index until there are 26 regions, balanced by population.',
    spec: withLensPreset(
      { ...base, scope: { kind: 'canada' }, method: 'lens', n: 26, seed: 26 },
      'internal_colony',
    ),
  },
  {
    id: 'canada-14',
    name: 'Canada in 14 (capitals)',
    description:
      "Seeded growth from today's 13 provincial and territorial capitals and Ottawa: each region grows from its capital over the mesh, then refinement smooths the boundaries. The seed cells are pinned, so a region always keeps its own capital.",
    spec: {
      ...base,
      scope: { kind: 'canada' },
      method: 'seeded',
      n: 14,
      seed: 14,
      balance: null,
      capitalPoints: CAPITALS.map((c) => c.point),
      capitalNames: CAPITALS.map((c) => c.name),
    },
  },
  {
    id: 'dominion-1867-5',
    name: 'The Dominion of 1867 in 5',
    description:
      "Canada as it stood on 1 July 1867 — Ontario, Quebec, Nova Scotia and New Brunswick — taken from the atlas as one scope and balanced by population into five regions. The House of Cards entry point in docs/interop.md: it is the pack meridian.getScores reads there. Numbers are today's (2021 census) over 1867's land.",
    spec: {
      ...base,
      scope: { kind: 'atlasSovereign', sovereign: 'Canada' },
      date: '1867-07-01',
      method: 'balanced',
      n: 5,
      seed: 1867,
    },
  },
];
