import { withLensPreset, defaultSpec, type SplitSpec } from './split';

/**
 * The shipped presets (plan Phase 3 Sitting B §6, amended 2026-09-17). They are generated by
 * the engine, never drawn by hand: `npm run presets -w app` regenerates packs/ (repo root) from these
 * specs, and src/splitter/presets.test.ts fails if the committed packs no longer match.
 */

/** Today's legislatures, [lng, lat]: the 13 provincial and territorial capitals, then Ottawa. */
export const CAPITALS: { name: string; point: [number, number] }[] = [
  { name: "St. John's", point: [-52.7126, 47.5615] },
  { name: 'Charlottetown', point: [-63.1311, 46.2382] },
  { name: 'Halifax', point: [-63.5752, 44.6488] },
  { name: 'Fredericton', point: [-66.6431, 45.9636] },
  { name: 'Québec', point: [-71.2143, 46.8081] },
  { name: 'Toronto', point: [-79.3957, 43.6629] },
  { name: 'Winnipeg', point: [-97.147, 49.8844] },
  { name: 'Regina', point: [-104.6153, 50.4321] },
  { name: 'Edmonton', point: [-113.5064, 53.5335] },
  { name: 'Victoria', point: [-123.37, 48.4197] },
  { name: 'Whitehorse', point: [-135.0523, 60.7197] },
  { name: 'Yellowknife', point: [-114.3718, 62.454] },
  { name: 'Iqaluit', point: [-68.517, 63.7467] },
  { name: 'Ottawa', point: [-75.7009, 45.4236] },
];

export interface Preset {
  id: string;
  name: string;
  description: string;
  /** why the split is made this way, in prose; written into the pack's meta.premise */
  premise?: string;
  spec: SplitSpec;
}

const base = defaultSpec();

export const PRESETS: Preset[] = [
  {
    id: 'alberta-15',
    name: 'Alberta in 15 (economic lens)',
    description: 'Alberta bisected on the Economic lens until there are 15 regions, balanced by population.',
    spec: {
      ...withLensPreset(
        { ...base, scope: { kind: 'province', province: 'AB' }, method: 'lens', n: 15, seed: 15 },
        'economic',
      ),
    },
  },
  {
    id: 'canada-26',
    name: 'Canada in 26 (internal-colony index)',
    description:
      'Canada bisected on the internal-colony index until there are 26 regions, balanced by population.',
    spec: withLensPreset(
      { ...base, scope: { kind: 'canada' }, method: 'lens', n: 26, seed: 26 },
      'internal_colony',
    ),
  },
  {
    id: 'canada-14',
    name: 'Canada in 14 (capitals)',
    description:
      "Seeded growth from today's 13 provincial and territorial capitals and Ottawa: each region grows from its capital over the mesh, then refinement smooths the boundaries. The seed cells are pinned, so a region always keeps its own capital.",
    spec: {
      ...base,
      scope: { kind: 'canada' },
      method: 'seeded',
      n: 14,
      seed: 14,
      balance: null,
      capitalPoints: CAPITALS.map((c) => c.point),
      capitalNames: CAPITALS.map((c) => c.name),
    },
  },
  {
    id: 'dominion-1867-5',
    name: 'The Dominion of 1867 in 5',
    description:
      "Canada as it stood on 1 July 1867 — Ontario, Quebec, Nova Scotia and New Brunswick — taken from the atlas as one scope and balanced by population into five regions. The House of Cards entry point in docs/interop.md: it is the pack meridian.getScores reads there. Numbers are today's (2021 census) over 1867's land. Its 105 cells in today's Labrador, between 52° and 53°N, follow the atlas's 1867 reading of interior Labrador: Quebec ran to the St. Lawrence side of the height of land, and only the Atlantic slope and Newfoundland's coast strip were outside it, until the 1927 award.",
    spec: {
      ...base,
      scope: { kind: 'atlasSovereign', sovereign: 'Canada' },
      date: '1867-07-01',
      method: 'balanced',
      n: 5,
      seed: 1867,
    },
  },
  {
    id: 'acadie-2',
    name: 'Acadie and the Maritimes',
    description:
      "Nova Scotia, New Brunswick and Prince Edward Island as one scope, bisected on French mother tongue into two, refined with hard contiguity. The more francophone region is named Acadie, the other the Maritimes. This is the 'Acadian Maritimes' of docs/vision.md §8.",
    premise:
      "Acadie is a people before it is a place: no Acadian province has ever existed, and the Acadians of 1755 lived in what are now Nova Scotia, New Brunswick and Prince Edward Island. This pack asks where an Acadian province would be if the three Maritime provinces were redrawn on language alone. It takes their 2021 census cells as one scope, bisects them on the share of French mother tongue, and lets refinement move the line while every region stays in one piece, with no population target. The francophone side is named Acadie and the rest the Maritimes. Contiguity is hard, so Acadie is one piece: northern and eastern New Brunswick, from Madawaska and Restigouche to the Acadian Peninsula, Kent and Moncton–Dieppe, with the thinly peopled interior that joins them, and one cell of Prince Edward Island's Évangéline region, at Wellington, joined across the Northumberland Strait by one of the mesh's sea crossings. The rest of Évangéline and the Acadian communities of Nova Scotia (Clare, Argyle, Chéticamp, Isle Madame) are too small and too far away to join it, and stay in the Maritimes. French is measured as mother tongue, not identity or ancestry, so the line is where French is the language people first learned, as the 2021 census counted it, not where Acadians live or lived.",
    spec: {
      ...base,
      scope: { kind: 'provinces', provinces: ['NB', 'NS', 'PE'] },
      method: 'lens',
      n: 2,
      seed: 2,
      lensPreset: null,
      lens: { french_share: 1 },
      balance: null,
      contiguity: 'hard',
      // The lens counts in refinement too, so the line follows the language rather than a province.
      weights: { ...base.weights, lens: 1 },
      nameBy: { column: 'french_share', names: ['Acadie', 'Maritimes'] },
    },
  },
];
